name: Unit Tests

on: [push, pull_request]

jobs:
  line-count:
    name: Less than 1000 lines
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install sloccount
      - name: Verify less than 1000 lines
        run: if [ $(sloccount fastwsgi.py fastwsgi/ | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 1000 ]; then exit 1; fi
    
  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -e '.[testing]'
      - name: Run unit tests
        run: python -m pytest -s -v